### ISSUE TITLE
harvest-image.py doesn't work

### ISSUE THREAD

**Issue by jiyaoweng** [Q42/SimpleOAIHarvester#3]
When running the script and got following error at beginning (after saving batch: 0.xml)
Traceback (most recent call last):
  File "harvest-images.py", line 148, in <module>
    token, countRecords = harvest(url)
  File "harvest-images.py", line 81, in harvest
    handleRecord(record)
  File "harvest-images.py", line 104, in handleRecord
    retrieveImages(record)
  File "harvest-images.py", line 113, in retrieveImages
    imageUrl = urls[0] # + '&100x100'
IndexError: list index out of range

Python version  2.7.13

**Comment by remcoder** [comment]
Could you post the xml file that you got?
